### PR TITLE
Fix warnings and code reformat

### PR DESCRIPTION
**Pull request by ghost**
Code formatted for nice view.
And removed tracy warning in function onBeforeRender() - added <if> statement to check user session.

### CODE REVIEW

**Comment by ghost** [comment]
Updated file openvk/Web/Themes/Themepacks.

**Review by veselcraft — CHANGES_REQUESTED** [review]
Codestyle is awful, not OVK standardized

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
@FireFox1121 huyok

**Pull request closed without merging**
