### PR TITLE
Add Indonesian translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by veselcraft** [comment]
Thank you for this pull request! If you would be an maintainer of your language, you can join our private Telegram translators group by this link: https://t.me/+FK_sxCgMtL8zYWE6

**Comment by ghost** [comment]
So... I support the effort to help our project, it is very good. However, there are some minor issues with the translation:

1. ~~"online" and "was_online" do not mean the same thing. The first is output if the user is currently online, while the second is only output if the user left the site with the message (e.g. "was online 6 Feb at 06:09 PM"). *But if "Aktif" literally means "Online" and "was online," then I don't see the problem.*~~
2. A lot of lines have been skipped. (UPD: not that much)
3. #492 with a new commit was created as a new PR, although it could have been done in this PR. (*nothing wrong with that, don't worry*)

And probably a few other small problems that I haven't noticed yet when I've scrolled through the whole list of strings...

You don't need to push yourself, really. If you need to work on the translation, then do it.

**Comment by themohooks** [comment]
> Thank you for this pull request! If you would be an maintainer of your language, you can join our private Telegram translators group by this link: https://t.me/+FK_sxCgMtL8zYWE6

группа из приватной стала в публичную

**Comment by ghost** [comment]
> Thank you for this pull request! If you would be an maintainer of your language, you can join our private Telegram translators group by this link: ...

I'm not sure if they have a Telegram account tbh...

**Comment by ghost** [comment]
> Thank you for this pull request! If you would be an maintainer of your language, you can join our private Telegram translators group by this link: https://t.me/+FK_sxCgMtL8zYWE6

sorry kinda late to reply,i'll if u pleased..
thanks for the acceptance..

**Comment by ayaaop** [comment]
@loliconazter ээ а чё меня в эту беседу не включили

**Comment by ghost** [comment]
Okay, your locale is now on OpenVK! Don't forget to work on it though, so come back to it when you have free time.

**Pull request merged**
