### PR TITLE
Allow adding comments to group admins

### PR DESCRIPTION
**Pull request by maksalees**
This PR allows you to add a comment to group administrators, which will be displayed in the list of administrators.
You can add a comment to the administrator in the settings.

Screenshot_20211105_115432

Screenshot_20211106_125044

After that, it will be displayed in the settings and in the block with the list of administrators (if enabled). Also, if only the group owner is shown in the block, the comment will also be displayed.

Screenshot_20211106_125425

image

To delete a comment to the administrator, you just need to set an empty comment to it.

This PR uses a new string from openvk/locales#14.

### CODE REVIEW

**Comment by WerySkok** [comment]
Can you add Hide/Show parameter?

**Comment by maksalees** [comment]
> Can you add Hide/Show parameter?

Add ability to turn off the display of comments publicly?

**Comment by WerySkok** [comment]
> Add ability to turn off the display of comments publicly?

No, add the ability to turn off the display of one of admins.

**Comment by maksalees** [comment]
> > Add ability to turn off the display of comments publicly?
> 
> No, add the ability to turn off the display of one of admins.

It is possible to delete a comment. You mean disabling the display of one administrator's comment publicly?

**Comment by maksalees** [comment]
> > Add ability to turn off the display of comments publicly?
> 
> No, add the ability to turn off the display of one of admins.

Understood. But this is a topic for a separate PR

**Comment by veselcraft** [comment]
No, this feature should be here

**Comment by maksalees** [comment]
> No, this feature should be here

Why? This PR just adds the ability to add comments. It seems to me that adding additional functionality here that is not related to comments is not very good. Well ok

**Comment by veselcraft** [comment]
I also like to see that design for "Admins"
изображение
or
изображение

**Comment by maksalees** [comment]
> I also like to see that design for "Admins" изображение or изображение

Ok i will implement it

**Comment by veselcraft** [comment]
> 
> 
> > No, this feature should be here
> 
> Why? This PR just adds the ability to add comments. It seems to me that adding additional functionality here that is not related to comments is not very good. Well ok

Alright, i understand that. I'll accept your PL after design thing 👌

**Comment by maksalees** [comment]
Made, it remains only to commit. I'll add the "All" button in a separate PR along with the ability to hide admins

image

**Comment by veselcraft** [comment]
This looks good!

**Comment by maksalees** [comment]
@veselcraft Avatars of different sizes look strange. Should it be fixed or left as it is? And whether to make the mode of displaying only the creator the same?
image

**Comment by celestora** [comment]
> Should it be fixed or left as it is?

I believe since this feature appeared in newer VK, "avatar type" setting should not be honoured here and avatars must be cropped forcifully. But I'll leave this for @veselcraft to decide.

Also: would it be possible for you to "stick" user's name to top, regardless of comment presence? Like this:
image

**Comment by veselcraft** [comment]
> 
> 
> @veselcraft Avatars of different sizes look strange. Should it be fixed or left as it is? And whether to make the mode of displaying only the creator the same? image

It should be fixed

**Comment by maksalees** [comment]
> > Should it be fixed or left as it is?
> 
> I believe since this feature appeared in newer VK, "avatar type" setting should not be honoured here and avatars must be cropped forcifully. But I'll leave this for @veselcraft to decide.
> 
> Also: would it be possible for you to "stick" user's name to top, regardless of comment presence? Like this: image

Yes I can

**Comment by maksalees** [comment]
> > @veselcraft Avatars of different sizes look strange. Should it be fixed or left as it is? And whether to make the mode of displaying only the creator the same? image
> 
> It should be fixed

Can I just stretch the avatar?
image

**Comment by celestora** [comment]
> Can I just stretch?

No, please add `object-fit: cover;` too :3

**Comment by maksalees** [comment]
Done
image

**Comment by maksalees** [comment]
Show only the group creator this way?
image

**Comment by celestora** [comment]
Yeah, that's satisfactory

**Comment by maksalees** [comment]
However, I don't think that in the absence of a comment on the creator, sticking the name to the top looks good.  Maybe in this case, can I make the centering of the name (only when displaying one creator)?
image

**Comment by veselcraft** [comment]
> 
> 
> However, I don't think that in the absence of a comment on the creator, sticking the name to the top looks good. Maybe in this case, can I make the centering of the name (only when displaying one creator)? image

Yep, center it

**Comment by maksalees** [comment]
@veselcraft Everything is done, you can merge

**Comment by maksalees** [comment]
@veselcraft Also merge openvk/locales#14 to keep things cool

**Pull request merged**
