### PR TITLE
locales: Add missing Turkish translations

### PR DESCRIPTION
**Pull request by windowzytch**
Signed-off-by: Wind/owZ <windowz414@gnuweeb.org>

### CODE REVIEW

**Comment by veselcraft** [comment]
where is "deceased_person"?

**Comment by windowzytch** [comment]
> where is "deceased_person"?

Ah, sorry. Amending right now.

**Comment by windowzytch** [comment]
> where is "deceased_person"?

Amended just now. If there are no more mistakes, you can merge right away.

**Comment by veselcraft** [comment]
Whoops, sorry, didn't saw new comment. I'll push that translate right now

**Pull request merged**
