### PR TITLE
General fixes to controls

### PR DESCRIPTION
**Pull request by SigmaTel71**
### Purpose

Make input controls consistent with default OpenVK color scheme (which is grayscale)

### What was done
- ~~radio controls are converted from color to grayscale~~
- ~~checkbox controls are converted from color to grayscale~~
- radio and checkbox controls' borders turned gray, the checkmark/bullet tint is darker

### Additional fixes
- checkboxes are 15x14, not 14x14, as their texture is 15px wide
- enabled hover-checked state both for checkboxes and radio controls

image

### CODE REVIEW

**Comment by veselcraft** [comment]
Checkmarks looks like disabled. Is there any other color or fix for that?

**Comment by SigmaTel71** [comment]
Perhaps we can make them pitch black (`#000000`)? But it would look too noticeable anyway, like blue ones were.

**Comment by veselcraft** [comment]
May we have blue checkmarks, but darker?

**Comment by SigmaTel71** [comment]
Will this tint work (the top checkmark is modified, the bottom left original for comparison)? The new tint uses `#3b5977` for symbol, `#c5cace` for shadow.
image

**Comment by SigmaTel71** [comment]
The full atlas will look like this.
checkbox
image

**Comment by veselcraft** [comment]
This looks allright

**Comment by SigmaTel71** [comment]
Given that, I also update radio controls to follow this color choice. In addition, it also fixes (actually implements) hover-checked state that was present in original stylesheets.
image

**Pull request merged**
